/**
 * generated by Xtext 2.27.0.M2
 */
package br.ufscar.dc.compiladores.alguma.alguma;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see br.ufscar.dc.compiladores.alguma.alguma.AlgumaFactory
 * @model kind="package"
 * @generated
 */
public interface AlgumaPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "alguma";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.ufscar.br/dc/compiladores/alguma/Alguma";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "alguma";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  AlgumaPackage eINSTANCE = br.ufscar.dc.compiladores.alguma.alguma.impl.AlgumaPackageImpl.init();

  /**
   * The meta object id for the '{@link br.ufscar.dc.compiladores.alguma.alguma.impl.ProgramaImpl <em>Programa</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see br.ufscar.dc.compiladores.alguma.alguma.impl.ProgramaImpl
   * @see br.ufscar.dc.compiladores.alguma.alguma.impl.AlgumaPackageImpl#getPrograma()
   * @generated
   */
  int PROGRAMA = 0;

  /**
   * The feature id for the '<em><b>Declaracoes</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROGRAMA__DECLARACOES = 0;

  /**
   * The feature id for the '<em><b>Comandos</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROGRAMA__COMANDOS = 1;

  /**
   * The number of structural features of the '<em>Programa</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROGRAMA_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link br.ufscar.dc.compiladores.alguma.alguma.impl.DeclaracaoImpl <em>Declaracao</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see br.ufscar.dc.compiladores.alguma.alguma.impl.DeclaracaoImpl
   * @see br.ufscar.dc.compiladores.alguma.alguma.impl.AlgumaPackageImpl#getDeclaracao()
   * @generated
   */
  int DECLARACAO = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DECLARACAO__NAME = 0;

  /**
   * The feature id for the '<em><b>Tipo</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DECLARACAO__TIPO = 1;

  /**
   * The number of structural features of the '<em>Declaracao</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DECLARACAO_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link br.ufscar.dc.compiladores.alguma.alguma.impl.ExpressaoAritmeticaImpl <em>Expressao Aritmetica</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see br.ufscar.dc.compiladores.alguma.alguma.impl.ExpressaoAritmeticaImpl
   * @see br.ufscar.dc.compiladores.alguma.alguma.impl.AlgumaPackageImpl#getExpressaoAritmetica()
   * @generated
   */
  int EXPRESSAO_ARITMETICA = 2;

  /**
   * The feature id for the '<em><b>Termo1</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSAO_ARITMETICA__TERMO1 = 0;

  /**
   * The feature id for the '<em><b>Outros Termos</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSAO_ARITMETICA__OUTROS_TERMOS = 1;

  /**
   * The number of structural features of the '<em>Expressao Aritmetica</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSAO_ARITMETICA_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link br.ufscar.dc.compiladores.alguma.alguma.impl.OutroTermoAritmeticoImpl <em>Outro Termo Aritmetico</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see br.ufscar.dc.compiladores.alguma.alguma.impl.OutroTermoAritmeticoImpl
   * @see br.ufscar.dc.compiladores.alguma.alguma.impl.AlgumaPackageImpl#getOutroTermoAritmetico()
   * @generated
   */
  int OUTRO_TERMO_ARITMETICO = 3;

  /**
   * The feature id for the '<em><b>Operador</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OUTRO_TERMO_ARITMETICO__OPERADOR = 0;

  /**
   * The feature id for the '<em><b>Termo</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OUTRO_TERMO_ARITMETICO__TERMO = 1;

  /**
   * The number of structural features of the '<em>Outro Termo Aritmetico</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OUTRO_TERMO_ARITMETICO_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link br.ufscar.dc.compiladores.alguma.alguma.impl.TermoAritmeticoImpl <em>Termo Aritmetico</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see br.ufscar.dc.compiladores.alguma.alguma.impl.TermoAritmeticoImpl
   * @see br.ufscar.dc.compiladores.alguma.alguma.impl.AlgumaPackageImpl#getTermoAritmetico()
   * @generated
   */
  int TERMO_ARITMETICO = 4;

  /**
   * The feature id for the '<em><b>Fator1</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TERMO_ARITMETICO__FATOR1 = 0;

  /**
   * The feature id for the '<em><b>Outros Fatores</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TERMO_ARITMETICO__OUTROS_FATORES = 1;

  /**
   * The number of structural features of the '<em>Termo Aritmetico</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TERMO_ARITMETICO_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link br.ufscar.dc.compiladores.alguma.alguma.impl.OutroFatorAritmeticoImpl <em>Outro Fator Aritmetico</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see br.ufscar.dc.compiladores.alguma.alguma.impl.OutroFatorAritmeticoImpl
   * @see br.ufscar.dc.compiladores.alguma.alguma.impl.AlgumaPackageImpl#getOutroFatorAritmetico()
   * @generated
   */
  int OUTRO_FATOR_ARITMETICO = 5;

  /**
   * The feature id for the '<em><b>Operador</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OUTRO_FATOR_ARITMETICO__OPERADOR = 0;

  /**
   * The feature id for the '<em><b>Fator</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OUTRO_FATOR_ARITMETICO__FATOR = 1;

  /**
   * The number of structural features of the '<em>Outro Fator Aritmetico</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OUTRO_FATOR_ARITMETICO_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link br.ufscar.dc.compiladores.alguma.alguma.impl.FatorAritmeticoImpl <em>Fator Aritmetico</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see br.ufscar.dc.compiladores.alguma.alguma.impl.FatorAritmeticoImpl
   * @see br.ufscar.dc.compiladores.alguma.alguma.impl.AlgumaPackageImpl#getFatorAritmetico()
   * @generated
   */
  int FATOR_ARITMETICO = 6;

  /**
   * The number of structural features of the '<em>Fator Aritmetico</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FATOR_ARITMETICO_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link br.ufscar.dc.compiladores.alguma.alguma.impl.FatorNumeroImpl <em>Fator Numero</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see br.ufscar.dc.compiladores.alguma.alguma.impl.FatorNumeroImpl
   * @see br.ufscar.dc.compiladores.alguma.alguma.impl.AlgumaPackageImpl#getFatorNumero()
   * @generated
   */
  int FATOR_NUMERO = 7;

  /**
   * The feature id for the '<em><b>Numero</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FATOR_NUMERO__NUMERO = FATOR_ARITMETICO_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Fator Numero</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FATOR_NUMERO_FEATURE_COUNT = FATOR_ARITMETICO_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link br.ufscar.dc.compiladores.alguma.alguma.impl.FatorVariavelImpl <em>Fator Variavel</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see br.ufscar.dc.compiladores.alguma.alguma.impl.FatorVariavelImpl
   * @see br.ufscar.dc.compiladores.alguma.alguma.impl.AlgumaPackageImpl#getFatorVariavel()
   * @generated
   */
  int FATOR_VARIAVEL = 8;

  /**
   * The feature id for the '<em><b>Variavel</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FATOR_VARIAVEL__VARIAVEL = FATOR_ARITMETICO_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Fator Variavel</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FATOR_VARIAVEL_FEATURE_COUNT = FATOR_ARITMETICO_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link br.ufscar.dc.compiladores.alguma.alguma.impl.FatorSubExpressaoImpl <em>Fator Sub Expressao</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see br.ufscar.dc.compiladores.alguma.alguma.impl.FatorSubExpressaoImpl
   * @see br.ufscar.dc.compiladores.alguma.alguma.impl.AlgumaPackageImpl#getFatorSubExpressao()
   * @generated
   */
  int FATOR_SUB_EXPRESSAO = 9;

  /**
   * The feature id for the '<em><b>Expressao</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FATOR_SUB_EXPRESSAO__EXPRESSAO = FATOR_ARITMETICO_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Fator Sub Expressao</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FATOR_SUB_EXPRESSAO_FEATURE_COUNT = FATOR_ARITMETICO_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link br.ufscar.dc.compiladores.alguma.alguma.impl.ExpressaoRelacionalImpl <em>Expressao Relacional</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see br.ufscar.dc.compiladores.alguma.alguma.impl.ExpressaoRelacionalImpl
   * @see br.ufscar.dc.compiladores.alguma.alguma.impl.AlgumaPackageImpl#getExpressaoRelacional()
   * @generated
   */
  int EXPRESSAO_RELACIONAL = 10;

  /**
   * The feature id for the '<em><b>Termo1</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSAO_RELACIONAL__TERMO1 = 0;

  /**
   * The feature id for the '<em><b>Outros Termos</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSAO_RELACIONAL__OUTROS_TERMOS = 1;

  /**
   * The number of structural features of the '<em>Expressao Relacional</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSAO_RELACIONAL_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link br.ufscar.dc.compiladores.alguma.alguma.impl.OutroTermoRelacionalImpl <em>Outro Termo Relacional</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see br.ufscar.dc.compiladores.alguma.alguma.impl.OutroTermoRelacionalImpl
   * @see br.ufscar.dc.compiladores.alguma.alguma.impl.AlgumaPackageImpl#getOutroTermoRelacional()
   * @generated
   */
  int OUTRO_TERMO_RELACIONAL = 11;

  /**
   * The feature id for the '<em><b>Operador</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OUTRO_TERMO_RELACIONAL__OPERADOR = 0;

  /**
   * The feature id for the '<em><b>Termo</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OUTRO_TERMO_RELACIONAL__TERMO = 1;

  /**
   * The number of structural features of the '<em>Outro Termo Relacional</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OUTRO_TERMO_RELACIONAL_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link br.ufscar.dc.compiladores.alguma.alguma.impl.TermoRelacionalImpl <em>Termo Relacional</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see br.ufscar.dc.compiladores.alguma.alguma.impl.TermoRelacionalImpl
   * @see br.ufscar.dc.compiladores.alguma.alguma.impl.AlgumaPackageImpl#getTermoRelacional()
   * @generated
   */
  int TERMO_RELACIONAL = 12;

  /**
   * The number of structural features of the '<em>Termo Relacional</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TERMO_RELACIONAL_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link br.ufscar.dc.compiladores.alguma.alguma.impl.TermoComparacaoRelacionalImpl <em>Termo Comparacao Relacional</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see br.ufscar.dc.compiladores.alguma.alguma.impl.TermoComparacaoRelacionalImpl
   * @see br.ufscar.dc.compiladores.alguma.alguma.impl.AlgumaPackageImpl#getTermoComparacaoRelacional()
   * @generated
   */
  int TERMO_COMPARACAO_RELACIONAL = 13;

  /**
   * The feature id for the '<em><b>Exp1</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TERMO_COMPARACAO_RELACIONAL__EXP1 = TERMO_RELACIONAL_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Op Rel</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TERMO_COMPARACAO_RELACIONAL__OP_REL = TERMO_RELACIONAL_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Exp2</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TERMO_COMPARACAO_RELACIONAL__EXP2 = TERMO_RELACIONAL_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Termo Comparacao Relacional</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TERMO_COMPARACAO_RELACIONAL_FEATURE_COUNT = TERMO_RELACIONAL_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link br.ufscar.dc.compiladores.alguma.alguma.impl.TermoSubExpressaoRelacionalImpl <em>Termo Sub Expressao Relacional</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see br.ufscar.dc.compiladores.alguma.alguma.impl.TermoSubExpressaoRelacionalImpl
   * @see br.ufscar.dc.compiladores.alguma.alguma.impl.AlgumaPackageImpl#getTermoSubExpressaoRelacional()
   * @generated
   */
  int TERMO_SUB_EXPRESSAO_RELACIONAL = 14;

  /**
   * The feature id for the '<em><b>Exp Rel</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TERMO_SUB_EXPRESSAO_RELACIONAL__EXP_REL = TERMO_RELACIONAL_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Termo Sub Expressao Relacional</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TERMO_SUB_EXPRESSAO_RELACIONAL_FEATURE_COUNT = TERMO_RELACIONAL_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link br.ufscar.dc.compiladores.alguma.alguma.impl.ComandoImpl <em>Comando</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see br.ufscar.dc.compiladores.alguma.alguma.impl.ComandoImpl
   * @see br.ufscar.dc.compiladores.alguma.alguma.impl.AlgumaPackageImpl#getComando()
   * @generated
   */
  int COMANDO = 15;

  /**
   * The number of structural features of the '<em>Comando</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMANDO_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link br.ufscar.dc.compiladores.alguma.alguma.impl.ComandoAtribuicaoImpl <em>Comando Atribuicao</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see br.ufscar.dc.compiladores.alguma.alguma.impl.ComandoAtribuicaoImpl
   * @see br.ufscar.dc.compiladores.alguma.alguma.impl.AlgumaPackageImpl#getComandoAtribuicao()
   * @generated
   */
  int COMANDO_ATRIBUICAO = 16;

  /**
   * The feature id for the '<em><b>Exp</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMANDO_ATRIBUICAO__EXP = COMANDO_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Variavel</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMANDO_ATRIBUICAO__VARIAVEL = COMANDO_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Comando Atribuicao</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMANDO_ATRIBUICAO_FEATURE_COUNT = COMANDO_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link br.ufscar.dc.compiladores.alguma.alguma.impl.ComandoEntradaImpl <em>Comando Entrada</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see br.ufscar.dc.compiladores.alguma.alguma.impl.ComandoEntradaImpl
   * @see br.ufscar.dc.compiladores.alguma.alguma.impl.AlgumaPackageImpl#getComandoEntrada()
   * @generated
   */
  int COMANDO_ENTRADA = 17;

  /**
   * The feature id for the '<em><b>Variavel</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMANDO_ENTRADA__VARIAVEL = COMANDO_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Comando Entrada</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMANDO_ENTRADA_FEATURE_COUNT = COMANDO_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link br.ufscar.dc.compiladores.alguma.alguma.impl.ComandoSaidaImpl <em>Comando Saida</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see br.ufscar.dc.compiladores.alguma.alguma.impl.ComandoSaidaImpl
   * @see br.ufscar.dc.compiladores.alguma.alguma.impl.AlgumaPackageImpl#getComandoSaida()
   * @generated
   */
  int COMANDO_SAIDA = 18;

  /**
   * The feature id for the '<em><b>Variavel</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMANDO_SAIDA__VARIAVEL = COMANDO_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Comando Saida</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMANDO_SAIDA_FEATURE_COUNT = COMANDO_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link br.ufscar.dc.compiladores.alguma.alguma.impl.ComandoCondicaoImpl <em>Comando Condicao</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see br.ufscar.dc.compiladores.alguma.alguma.impl.ComandoCondicaoImpl
   * @see br.ufscar.dc.compiladores.alguma.alguma.impl.AlgumaPackageImpl#getComandoCondicao()
   * @generated
   */
  int COMANDO_CONDICAO = 19;

  /**
   * The feature id for the '<em><b>Exp</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMANDO_CONDICAO__EXP = COMANDO_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Cmd1</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMANDO_CONDICAO__CMD1 = COMANDO_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Cmd2</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMANDO_CONDICAO__CMD2 = COMANDO_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Comando Condicao</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMANDO_CONDICAO_FEATURE_COUNT = COMANDO_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link br.ufscar.dc.compiladores.alguma.alguma.impl.ComandoRepeticaoImpl <em>Comando Repeticao</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see br.ufscar.dc.compiladores.alguma.alguma.impl.ComandoRepeticaoImpl
   * @see br.ufscar.dc.compiladores.alguma.alguma.impl.AlgumaPackageImpl#getComandoRepeticao()
   * @generated
   */
  int COMANDO_REPETICAO = 20;

  /**
   * The feature id for the '<em><b>Exp</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMANDO_REPETICAO__EXP = COMANDO_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Cmd</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMANDO_REPETICAO__CMD = COMANDO_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Comando Repeticao</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMANDO_REPETICAO_FEATURE_COUNT = COMANDO_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link br.ufscar.dc.compiladores.alguma.alguma.impl.SubAlgoritmoImpl <em>Sub Algoritmo</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see br.ufscar.dc.compiladores.alguma.alguma.impl.SubAlgoritmoImpl
   * @see br.ufscar.dc.compiladores.alguma.alguma.impl.AlgumaPackageImpl#getSubAlgoritmo()
   * @generated
   */
  int SUB_ALGORITMO = 21;

  /**
   * The feature id for the '<em><b>Comandos</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SUB_ALGORITMO__COMANDOS = COMANDO_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Sub Algoritmo</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SUB_ALGORITMO_FEATURE_COUNT = COMANDO_FEATURE_COUNT + 1;


  /**
   * Returns the meta object for class '{@link br.ufscar.dc.compiladores.alguma.alguma.Programa <em>Programa</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Programa</em>'.
   * @see br.ufscar.dc.compiladores.alguma.alguma.Programa
   * @generated
   */
  EClass getPrograma();

  /**
   * Returns the meta object for the containment reference list '{@link br.ufscar.dc.compiladores.alguma.alguma.Programa#getDeclaracoes <em>Declaracoes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Declaracoes</em>'.
   * @see br.ufscar.dc.compiladores.alguma.alguma.Programa#getDeclaracoes()
   * @see #getPrograma()
   * @generated
   */
  EReference getPrograma_Declaracoes();

  /**
   * Returns the meta object for the containment reference list '{@link br.ufscar.dc.compiladores.alguma.alguma.Programa#getComandos <em>Comandos</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Comandos</em>'.
   * @see br.ufscar.dc.compiladores.alguma.alguma.Programa#getComandos()
   * @see #getPrograma()
   * @generated
   */
  EReference getPrograma_Comandos();

  /**
   * Returns the meta object for class '{@link br.ufscar.dc.compiladores.alguma.alguma.Declaracao <em>Declaracao</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Declaracao</em>'.
   * @see br.ufscar.dc.compiladores.alguma.alguma.Declaracao
   * @generated
   */
  EClass getDeclaracao();

  /**
   * Returns the meta object for the attribute '{@link br.ufscar.dc.compiladores.alguma.alguma.Declaracao#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see br.ufscar.dc.compiladores.alguma.alguma.Declaracao#getName()
   * @see #getDeclaracao()
   * @generated
   */
  EAttribute getDeclaracao_Name();

  /**
   * Returns the meta object for the attribute '{@link br.ufscar.dc.compiladores.alguma.alguma.Declaracao#getTipo <em>Tipo</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Tipo</em>'.
   * @see br.ufscar.dc.compiladores.alguma.alguma.Declaracao#getTipo()
   * @see #getDeclaracao()
   * @generated
   */
  EAttribute getDeclaracao_Tipo();

  /**
   * Returns the meta object for class '{@link br.ufscar.dc.compiladores.alguma.alguma.ExpressaoAritmetica <em>Expressao Aritmetica</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Expressao Aritmetica</em>'.
   * @see br.ufscar.dc.compiladores.alguma.alguma.ExpressaoAritmetica
   * @generated
   */
  EClass getExpressaoAritmetica();

  /**
   * Returns the meta object for the containment reference '{@link br.ufscar.dc.compiladores.alguma.alguma.ExpressaoAritmetica#getTermo1 <em>Termo1</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Termo1</em>'.
   * @see br.ufscar.dc.compiladores.alguma.alguma.ExpressaoAritmetica#getTermo1()
   * @see #getExpressaoAritmetica()
   * @generated
   */
  EReference getExpressaoAritmetica_Termo1();

  /**
   * Returns the meta object for the containment reference list '{@link br.ufscar.dc.compiladores.alguma.alguma.ExpressaoAritmetica#getOutrosTermos <em>Outros Termos</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Outros Termos</em>'.
   * @see br.ufscar.dc.compiladores.alguma.alguma.ExpressaoAritmetica#getOutrosTermos()
   * @see #getExpressaoAritmetica()
   * @generated
   */
  EReference getExpressaoAritmetica_OutrosTermos();

  /**
   * Returns the meta object for class '{@link br.ufscar.dc.compiladores.alguma.alguma.OutroTermoAritmetico <em>Outro Termo Aritmetico</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Outro Termo Aritmetico</em>'.
   * @see br.ufscar.dc.compiladores.alguma.alguma.OutroTermoAritmetico
   * @generated
   */
  EClass getOutroTermoAritmetico();

  /**
   * Returns the meta object for the attribute '{@link br.ufscar.dc.compiladores.alguma.alguma.OutroTermoAritmetico#getOperador <em>Operador</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Operador</em>'.
   * @see br.ufscar.dc.compiladores.alguma.alguma.OutroTermoAritmetico#getOperador()
   * @see #getOutroTermoAritmetico()
   * @generated
   */
  EAttribute getOutroTermoAritmetico_Operador();

  /**
   * Returns the meta object for the containment reference '{@link br.ufscar.dc.compiladores.alguma.alguma.OutroTermoAritmetico#getTermo <em>Termo</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Termo</em>'.
   * @see br.ufscar.dc.compiladores.alguma.alguma.OutroTermoAritmetico#getTermo()
   * @see #getOutroTermoAritmetico()
   * @generated
   */
  EReference getOutroTermoAritmetico_Termo();

  /**
   * Returns the meta object for class '{@link br.ufscar.dc.compiladores.alguma.alguma.TermoAritmetico <em>Termo Aritmetico</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Termo Aritmetico</em>'.
   * @see br.ufscar.dc.compiladores.alguma.alguma.TermoAritmetico
   * @generated
   */
  EClass getTermoAritmetico();

  /**
   * Returns the meta object for the containment reference '{@link br.ufscar.dc.compiladores.alguma.alguma.TermoAritmetico#getFator1 <em>Fator1</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Fator1</em>'.
   * @see br.ufscar.dc.compiladores.alguma.alguma.TermoAritmetico#getFator1()
   * @see #getTermoAritmetico()
   * @generated
   */
  EReference getTermoAritmetico_Fator1();

  /**
   * Returns the meta object for the containment reference list '{@link br.ufscar.dc.compiladores.alguma.alguma.TermoAritmetico#getOutrosFatores <em>Outros Fatores</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Outros Fatores</em>'.
   * @see br.ufscar.dc.compiladores.alguma.alguma.TermoAritmetico#getOutrosFatores()
   * @see #getTermoAritmetico()
   * @generated
   */
  EReference getTermoAritmetico_OutrosFatores();

  /**
   * Returns the meta object for class '{@link br.ufscar.dc.compiladores.alguma.alguma.OutroFatorAritmetico <em>Outro Fator Aritmetico</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Outro Fator Aritmetico</em>'.
   * @see br.ufscar.dc.compiladores.alguma.alguma.OutroFatorAritmetico
   * @generated
   */
  EClass getOutroFatorAritmetico();

  /**
   * Returns the meta object for the attribute '{@link br.ufscar.dc.compiladores.alguma.alguma.OutroFatorAritmetico#getOperador <em>Operador</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Operador</em>'.
   * @see br.ufscar.dc.compiladores.alguma.alguma.OutroFatorAritmetico#getOperador()
   * @see #getOutroFatorAritmetico()
   * @generated
   */
  EAttribute getOutroFatorAritmetico_Operador();

  /**
   * Returns the meta object for the containment reference '{@link br.ufscar.dc.compiladores.alguma.alguma.OutroFatorAritmetico#getFator <em>Fator</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Fator</em>'.
   * @see br.ufscar.dc.compiladores.alguma.alguma.OutroFatorAritmetico#getFator()
   * @see #getOutroFatorAritmetico()
   * @generated
   */
  EReference getOutroFatorAritmetico_Fator();

  /**
   * Returns the meta object for class '{@link br.ufscar.dc.compiladores.alguma.alguma.FatorAritmetico <em>Fator Aritmetico</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Fator Aritmetico</em>'.
   * @see br.ufscar.dc.compiladores.alguma.alguma.FatorAritmetico
   * @generated
   */
  EClass getFatorAritmetico();

  /**
   * Returns the meta object for class '{@link br.ufscar.dc.compiladores.alguma.alguma.FatorNumero <em>Fator Numero</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Fator Numero</em>'.
   * @see br.ufscar.dc.compiladores.alguma.alguma.FatorNumero
   * @generated
   */
  EClass getFatorNumero();

  /**
   * Returns the meta object for the attribute '{@link br.ufscar.dc.compiladores.alguma.alguma.FatorNumero#getNumero <em>Numero</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Numero</em>'.
   * @see br.ufscar.dc.compiladores.alguma.alguma.FatorNumero#getNumero()
   * @see #getFatorNumero()
   * @generated
   */
  EAttribute getFatorNumero_Numero();

  /**
   * Returns the meta object for class '{@link br.ufscar.dc.compiladores.alguma.alguma.FatorVariavel <em>Fator Variavel</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Fator Variavel</em>'.
   * @see br.ufscar.dc.compiladores.alguma.alguma.FatorVariavel
   * @generated
   */
  EClass getFatorVariavel();

  /**
   * Returns the meta object for the reference '{@link br.ufscar.dc.compiladores.alguma.alguma.FatorVariavel#getVariavel <em>Variavel</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Variavel</em>'.
   * @see br.ufscar.dc.compiladores.alguma.alguma.FatorVariavel#getVariavel()
   * @see #getFatorVariavel()
   * @generated
   */
  EReference getFatorVariavel_Variavel();

  /**
   * Returns the meta object for class '{@link br.ufscar.dc.compiladores.alguma.alguma.FatorSubExpressao <em>Fator Sub Expressao</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Fator Sub Expressao</em>'.
   * @see br.ufscar.dc.compiladores.alguma.alguma.FatorSubExpressao
   * @generated
   */
  EClass getFatorSubExpressao();

  /**
   * Returns the meta object for the containment reference '{@link br.ufscar.dc.compiladores.alguma.alguma.FatorSubExpressao#getExpressao <em>Expressao</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Expressao</em>'.
   * @see br.ufscar.dc.compiladores.alguma.alguma.FatorSubExpressao#getExpressao()
   * @see #getFatorSubExpressao()
   * @generated
   */
  EReference getFatorSubExpressao_Expressao();

  /**
   * Returns the meta object for class '{@link br.ufscar.dc.compiladores.alguma.alguma.ExpressaoRelacional <em>Expressao Relacional</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Expressao Relacional</em>'.
   * @see br.ufscar.dc.compiladores.alguma.alguma.ExpressaoRelacional
   * @generated
   */
  EClass getExpressaoRelacional();

  /**
   * Returns the meta object for the containment reference '{@link br.ufscar.dc.compiladores.alguma.alguma.ExpressaoRelacional#getTermo1 <em>Termo1</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Termo1</em>'.
   * @see br.ufscar.dc.compiladores.alguma.alguma.ExpressaoRelacional#getTermo1()
   * @see #getExpressaoRelacional()
   * @generated
   */
  EReference getExpressaoRelacional_Termo1();

  /**
   * Returns the meta object for the containment reference list '{@link br.ufscar.dc.compiladores.alguma.alguma.ExpressaoRelacional#getOutrosTermos <em>Outros Termos</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Outros Termos</em>'.
   * @see br.ufscar.dc.compiladores.alguma.alguma.ExpressaoRelacional#getOutrosTermos()
   * @see #getExpressaoRelacional()
   * @generated
   */
  EReference getExpressaoRelacional_OutrosTermos();

  /**
   * Returns the meta object for class '{@link br.ufscar.dc.compiladores.alguma.alguma.OutroTermoRelacional <em>Outro Termo Relacional</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Outro Termo Relacional</em>'.
   * @see br.ufscar.dc.compiladores.alguma.alguma.OutroTermoRelacional
   * @generated
   */
  EClass getOutroTermoRelacional();

  /**
   * Returns the meta object for the attribute '{@link br.ufscar.dc.compiladores.alguma.alguma.OutroTermoRelacional#getOperador <em>Operador</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Operador</em>'.
   * @see br.ufscar.dc.compiladores.alguma.alguma.OutroTermoRelacional#getOperador()
   * @see #getOutroTermoRelacional()
   * @generated
   */
  EAttribute getOutroTermoRelacional_Operador();

  /**
   * Returns the meta object for the containment reference '{@link br.ufscar.dc.compiladores.alguma.alguma.OutroTermoRelacional#getTermo <em>Termo</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Termo</em>'.
   * @see br.ufscar.dc.compiladores.alguma.alguma.OutroTermoRelacional#getTermo()
   * @see #getOutroTermoRelacional()
   * @generated
   */
  EReference getOutroTermoRelacional_Termo();

  /**
   * Returns the meta object for class '{@link br.ufscar.dc.compiladores.alguma.alguma.TermoRelacional <em>Termo Relacional</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Termo Relacional</em>'.
   * @see br.ufscar.dc.compiladores.alguma.alguma.TermoRelacional
   * @generated
   */
  EClass getTermoRelacional();

  /**
   * Returns the meta object for class '{@link br.ufscar.dc.compiladores.alguma.alguma.TermoComparacaoRelacional <em>Termo Comparacao Relacional</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Termo Comparacao Relacional</em>'.
   * @see br.ufscar.dc.compiladores.alguma.alguma.TermoComparacaoRelacional
   * @generated
   */
  EClass getTermoComparacaoRelacional();

  /**
   * Returns the meta object for the containment reference '{@link br.ufscar.dc.compiladores.alguma.alguma.TermoComparacaoRelacional#getExp1 <em>Exp1</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Exp1</em>'.
   * @see br.ufscar.dc.compiladores.alguma.alguma.TermoComparacaoRelacional#getExp1()
   * @see #getTermoComparacaoRelacional()
   * @generated
   */
  EReference getTermoComparacaoRelacional_Exp1();

  /**
   * Returns the meta object for the attribute '{@link br.ufscar.dc.compiladores.alguma.alguma.TermoComparacaoRelacional#getOpRel <em>Op Rel</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Op Rel</em>'.
   * @see br.ufscar.dc.compiladores.alguma.alguma.TermoComparacaoRelacional#getOpRel()
   * @see #getTermoComparacaoRelacional()
   * @generated
   */
  EAttribute getTermoComparacaoRelacional_OpRel();

  /**
   * Returns the meta object for the containment reference '{@link br.ufscar.dc.compiladores.alguma.alguma.TermoComparacaoRelacional#getExp2 <em>Exp2</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Exp2</em>'.
   * @see br.ufscar.dc.compiladores.alguma.alguma.TermoComparacaoRelacional#getExp2()
   * @see #getTermoComparacaoRelacional()
   * @generated
   */
  EReference getTermoComparacaoRelacional_Exp2();

  /**
   * Returns the meta object for class '{@link br.ufscar.dc.compiladores.alguma.alguma.TermoSubExpressaoRelacional <em>Termo Sub Expressao Relacional</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Termo Sub Expressao Relacional</em>'.
   * @see br.ufscar.dc.compiladores.alguma.alguma.TermoSubExpressaoRelacional
   * @generated
   */
  EClass getTermoSubExpressaoRelacional();

  /**
   * Returns the meta object for the containment reference '{@link br.ufscar.dc.compiladores.alguma.alguma.TermoSubExpressaoRelacional#getExpRel <em>Exp Rel</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Exp Rel</em>'.
   * @see br.ufscar.dc.compiladores.alguma.alguma.TermoSubExpressaoRelacional#getExpRel()
   * @see #getTermoSubExpressaoRelacional()
   * @generated
   */
  EReference getTermoSubExpressaoRelacional_ExpRel();

  /**
   * Returns the meta object for class '{@link br.ufscar.dc.compiladores.alguma.alguma.Comando <em>Comando</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Comando</em>'.
   * @see br.ufscar.dc.compiladores.alguma.alguma.Comando
   * @generated
   */
  EClass getComando();

  /**
   * Returns the meta object for class '{@link br.ufscar.dc.compiladores.alguma.alguma.ComandoAtribuicao <em>Comando Atribuicao</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Comando Atribuicao</em>'.
   * @see br.ufscar.dc.compiladores.alguma.alguma.ComandoAtribuicao
   * @generated
   */
  EClass getComandoAtribuicao();

  /**
   * Returns the meta object for the containment reference '{@link br.ufscar.dc.compiladores.alguma.alguma.ComandoAtribuicao#getExp <em>Exp</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Exp</em>'.
   * @see br.ufscar.dc.compiladores.alguma.alguma.ComandoAtribuicao#getExp()
   * @see #getComandoAtribuicao()
   * @generated
   */
  EReference getComandoAtribuicao_Exp();

  /**
   * Returns the meta object for the reference '{@link br.ufscar.dc.compiladores.alguma.alguma.ComandoAtribuicao#getVariavel <em>Variavel</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Variavel</em>'.
   * @see br.ufscar.dc.compiladores.alguma.alguma.ComandoAtribuicao#getVariavel()
   * @see #getComandoAtribuicao()
   * @generated
   */
  EReference getComandoAtribuicao_Variavel();

  /**
   * Returns the meta object for class '{@link br.ufscar.dc.compiladores.alguma.alguma.ComandoEntrada <em>Comando Entrada</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Comando Entrada</em>'.
   * @see br.ufscar.dc.compiladores.alguma.alguma.ComandoEntrada
   * @generated
   */
  EClass getComandoEntrada();

  /**
   * Returns the meta object for the reference '{@link br.ufscar.dc.compiladores.alguma.alguma.ComandoEntrada#getVariavel <em>Variavel</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Variavel</em>'.
   * @see br.ufscar.dc.compiladores.alguma.alguma.ComandoEntrada#getVariavel()
   * @see #getComandoEntrada()
   * @generated
   */
  EReference getComandoEntrada_Variavel();

  /**
   * Returns the meta object for class '{@link br.ufscar.dc.compiladores.alguma.alguma.ComandoSaida <em>Comando Saida</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Comando Saida</em>'.
   * @see br.ufscar.dc.compiladores.alguma.alguma.ComandoSaida
   * @generated
   */
  EClass getComandoSaida();

  /**
   * Returns the meta object for the reference '{@link br.ufscar.dc.compiladores.alguma.alguma.ComandoSaida#getVariavel <em>Variavel</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Variavel</em>'.
   * @see br.ufscar.dc.compiladores.alguma.alguma.ComandoSaida#getVariavel()
   * @see #getComandoSaida()
   * @generated
   */
  EReference getComandoSaida_Variavel();

  /**
   * Returns the meta object for class '{@link br.ufscar.dc.compiladores.alguma.alguma.ComandoCondicao <em>Comando Condicao</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Comando Condicao</em>'.
   * @see br.ufscar.dc.compiladores.alguma.alguma.ComandoCondicao
   * @generated
   */
  EClass getComandoCondicao();

  /**
   * Returns the meta object for the containment reference '{@link br.ufscar.dc.compiladores.alguma.alguma.ComandoCondicao#getExp <em>Exp</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Exp</em>'.
   * @see br.ufscar.dc.compiladores.alguma.alguma.ComandoCondicao#getExp()
   * @see #getComandoCondicao()
   * @generated
   */
  EReference getComandoCondicao_Exp();

  /**
   * Returns the meta object for the containment reference '{@link br.ufscar.dc.compiladores.alguma.alguma.ComandoCondicao#getCmd1 <em>Cmd1</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Cmd1</em>'.
   * @see br.ufscar.dc.compiladores.alguma.alguma.ComandoCondicao#getCmd1()
   * @see #getComandoCondicao()
   * @generated
   */
  EReference getComandoCondicao_Cmd1();

  /**
   * Returns the meta object for the containment reference '{@link br.ufscar.dc.compiladores.alguma.alguma.ComandoCondicao#getCmd2 <em>Cmd2</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Cmd2</em>'.
   * @see br.ufscar.dc.compiladores.alguma.alguma.ComandoCondicao#getCmd2()
   * @see #getComandoCondicao()
   * @generated
   */
  EReference getComandoCondicao_Cmd2();

  /**
   * Returns the meta object for class '{@link br.ufscar.dc.compiladores.alguma.alguma.ComandoRepeticao <em>Comando Repeticao</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Comando Repeticao</em>'.
   * @see br.ufscar.dc.compiladores.alguma.alguma.ComandoRepeticao
   * @generated
   */
  EClass getComandoRepeticao();

  /**
   * Returns the meta object for the containment reference '{@link br.ufscar.dc.compiladores.alguma.alguma.ComandoRepeticao#getExp <em>Exp</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Exp</em>'.
   * @see br.ufscar.dc.compiladores.alguma.alguma.ComandoRepeticao#getExp()
   * @see #getComandoRepeticao()
   * @generated
   */
  EReference getComandoRepeticao_Exp();

  /**
   * Returns the meta object for the containment reference '{@link br.ufscar.dc.compiladores.alguma.alguma.ComandoRepeticao#getCmd <em>Cmd</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Cmd</em>'.
   * @see br.ufscar.dc.compiladores.alguma.alguma.ComandoRepeticao#getCmd()
   * @see #getComandoRepeticao()
   * @generated
   */
  EReference getComandoRepeticao_Cmd();

  /**
   * Returns the meta object for class '{@link br.ufscar.dc.compiladores.alguma.alguma.SubAlgoritmo <em>Sub Algoritmo</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Sub Algoritmo</em>'.
   * @see br.ufscar.dc.compiladores.alguma.alguma.SubAlgoritmo
   * @generated
   */
  EClass getSubAlgoritmo();

  /**
   * Returns the meta object for the containment reference list '{@link br.ufscar.dc.compiladores.alguma.alguma.SubAlgoritmo#getComandos <em>Comandos</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Comandos</em>'.
   * @see br.ufscar.dc.compiladores.alguma.alguma.SubAlgoritmo#getComandos()
   * @see #getSubAlgoritmo()
   * @generated
   */
  EReference getSubAlgoritmo_Comandos();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  AlgumaFactory getAlgumaFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link br.ufscar.dc.compiladores.alguma.alguma.impl.ProgramaImpl <em>Programa</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see br.ufscar.dc.compiladores.alguma.alguma.impl.ProgramaImpl
     * @see br.ufscar.dc.compiladores.alguma.alguma.impl.AlgumaPackageImpl#getPrograma()
     * @generated
     */
    EClass PROGRAMA = eINSTANCE.getPrograma();

    /**
     * The meta object literal for the '<em><b>Declaracoes</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROGRAMA__DECLARACOES = eINSTANCE.getPrograma_Declaracoes();

    /**
     * The meta object literal for the '<em><b>Comandos</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROGRAMA__COMANDOS = eINSTANCE.getPrograma_Comandos();

    /**
     * The meta object literal for the '{@link br.ufscar.dc.compiladores.alguma.alguma.impl.DeclaracaoImpl <em>Declaracao</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see br.ufscar.dc.compiladores.alguma.alguma.impl.DeclaracaoImpl
     * @see br.ufscar.dc.compiladores.alguma.alguma.impl.AlgumaPackageImpl#getDeclaracao()
     * @generated
     */
    EClass DECLARACAO = eINSTANCE.getDeclaracao();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DECLARACAO__NAME = eINSTANCE.getDeclaracao_Name();

    /**
     * The meta object literal for the '<em><b>Tipo</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DECLARACAO__TIPO = eINSTANCE.getDeclaracao_Tipo();

    /**
     * The meta object literal for the '{@link br.ufscar.dc.compiladores.alguma.alguma.impl.ExpressaoAritmeticaImpl <em>Expressao Aritmetica</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see br.ufscar.dc.compiladores.alguma.alguma.impl.ExpressaoAritmeticaImpl
     * @see br.ufscar.dc.compiladores.alguma.alguma.impl.AlgumaPackageImpl#getExpressaoAritmetica()
     * @generated
     */
    EClass EXPRESSAO_ARITMETICA = eINSTANCE.getExpressaoAritmetica();

    /**
     * The meta object literal for the '<em><b>Termo1</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPRESSAO_ARITMETICA__TERMO1 = eINSTANCE.getExpressaoAritmetica_Termo1();

    /**
     * The meta object literal for the '<em><b>Outros Termos</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPRESSAO_ARITMETICA__OUTROS_TERMOS = eINSTANCE.getExpressaoAritmetica_OutrosTermos();

    /**
     * The meta object literal for the '{@link br.ufscar.dc.compiladores.alguma.alguma.impl.OutroTermoAritmeticoImpl <em>Outro Termo Aritmetico</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see br.ufscar.dc.compiladores.alguma.alguma.impl.OutroTermoAritmeticoImpl
     * @see br.ufscar.dc.compiladores.alguma.alguma.impl.AlgumaPackageImpl#getOutroTermoAritmetico()
     * @generated
     */
    EClass OUTRO_TERMO_ARITMETICO = eINSTANCE.getOutroTermoAritmetico();

    /**
     * The meta object literal for the '<em><b>Operador</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OUTRO_TERMO_ARITMETICO__OPERADOR = eINSTANCE.getOutroTermoAritmetico_Operador();

    /**
     * The meta object literal for the '<em><b>Termo</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OUTRO_TERMO_ARITMETICO__TERMO = eINSTANCE.getOutroTermoAritmetico_Termo();

    /**
     * The meta object literal for the '{@link br.ufscar.dc.compiladores.alguma.alguma.impl.TermoAritmeticoImpl <em>Termo Aritmetico</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see br.ufscar.dc.compiladores.alguma.alguma.impl.TermoAritmeticoImpl
     * @see br.ufscar.dc.compiladores.alguma.alguma.impl.AlgumaPackageImpl#getTermoAritmetico()
     * @generated
     */
    EClass TERMO_ARITMETICO = eINSTANCE.getTermoAritmetico();

    /**
     * The meta object literal for the '<em><b>Fator1</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TERMO_ARITMETICO__FATOR1 = eINSTANCE.getTermoAritmetico_Fator1();

    /**
     * The meta object literal for the '<em><b>Outros Fatores</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TERMO_ARITMETICO__OUTROS_FATORES = eINSTANCE.getTermoAritmetico_OutrosFatores();

    /**
     * The meta object literal for the '{@link br.ufscar.dc.compiladores.alguma.alguma.impl.OutroFatorAritmeticoImpl <em>Outro Fator Aritmetico</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see br.ufscar.dc.compiladores.alguma.alguma.impl.OutroFatorAritmeticoImpl
     * @see br.ufscar.dc.compiladores.alguma.alguma.impl.AlgumaPackageImpl#getOutroFatorAritmetico()
     * @generated
     */
    EClass OUTRO_FATOR_ARITMETICO = eINSTANCE.getOutroFatorAritmetico();

    /**
     * The meta object literal for the '<em><b>Operador</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OUTRO_FATOR_ARITMETICO__OPERADOR = eINSTANCE.getOutroFatorAritmetico_Operador();

    /**
     * The meta object literal for the '<em><b>Fator</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OUTRO_FATOR_ARITMETICO__FATOR = eINSTANCE.getOutroFatorAritmetico_Fator();

    /**
     * The meta object literal for the '{@link br.ufscar.dc.compiladores.alguma.alguma.impl.FatorAritmeticoImpl <em>Fator Aritmetico</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see br.ufscar.dc.compiladores.alguma.alguma.impl.FatorAritmeticoImpl
     * @see br.ufscar.dc.compiladores.alguma.alguma.impl.AlgumaPackageImpl#getFatorAritmetico()
     * @generated
     */
    EClass FATOR_ARITMETICO = eINSTANCE.getFatorAritmetico();

    /**
     * The meta object literal for the '{@link br.ufscar.dc.compiladores.alguma.alguma.impl.FatorNumeroImpl <em>Fator Numero</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see br.ufscar.dc.compiladores.alguma.alguma.impl.FatorNumeroImpl
     * @see br.ufscar.dc.compiladores.alguma.alguma.impl.AlgumaPackageImpl#getFatorNumero()
     * @generated
     */
    EClass FATOR_NUMERO = eINSTANCE.getFatorNumero();

    /**
     * The meta object literal for the '<em><b>Numero</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FATOR_NUMERO__NUMERO = eINSTANCE.getFatorNumero_Numero();

    /**
     * The meta object literal for the '{@link br.ufscar.dc.compiladores.alguma.alguma.impl.FatorVariavelImpl <em>Fator Variavel</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see br.ufscar.dc.compiladores.alguma.alguma.impl.FatorVariavelImpl
     * @see br.ufscar.dc.compiladores.alguma.alguma.impl.AlgumaPackageImpl#getFatorVariavel()
     * @generated
     */
    EClass FATOR_VARIAVEL = eINSTANCE.getFatorVariavel();

    /**
     * The meta object literal for the '<em><b>Variavel</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FATOR_VARIAVEL__VARIAVEL = eINSTANCE.getFatorVariavel_Variavel();

    /**
     * The meta object literal for the '{@link br.ufscar.dc.compiladores.alguma.alguma.impl.FatorSubExpressaoImpl <em>Fator Sub Expressao</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see br.ufscar.dc.compiladores.alguma.alguma.impl.FatorSubExpressaoImpl
     * @see br.ufscar.dc.compiladores.alguma.alguma.impl.AlgumaPackageImpl#getFatorSubExpressao()
     * @generated
     */
    EClass FATOR_SUB_EXPRESSAO = eINSTANCE.getFatorSubExpressao();

    /**
     * The meta object literal for the '<em><b>Expressao</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FATOR_SUB_EXPRESSAO__EXPRESSAO = eINSTANCE.getFatorSubExpressao_Expressao();

    /**
     * The meta object literal for the '{@link br.ufscar.dc.compiladores.alguma.alguma.impl.ExpressaoRelacionalImpl <em>Expressao Relacional</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see br.ufscar.dc.compiladores.alguma.alguma.impl.ExpressaoRelacionalImpl
     * @see br.ufscar.dc.compiladores.alguma.alguma.impl.AlgumaPackageImpl#getExpressaoRelacional()
     * @generated
     */
    EClass EXPRESSAO_RELACIONAL = eINSTANCE.getExpressaoRelacional();

    /**
     * The meta object literal for the '<em><b>Termo1</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPRESSAO_RELACIONAL__TERMO1 = eINSTANCE.getExpressaoRelacional_Termo1();

    /**
     * The meta object literal for the '<em><b>Outros Termos</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPRESSAO_RELACIONAL__OUTROS_TERMOS = eINSTANCE.getExpressaoRelacional_OutrosTermos();

    /**
     * The meta object literal for the '{@link br.ufscar.dc.compiladores.alguma.alguma.impl.OutroTermoRelacionalImpl <em>Outro Termo Relacional</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see br.ufscar.dc.compiladores.alguma.alguma.impl.OutroTermoRelacionalImpl
     * @see br.ufscar.dc.compiladores.alguma.alguma.impl.AlgumaPackageImpl#getOutroTermoRelacional()
     * @generated
     */
    EClass OUTRO_TERMO_RELACIONAL = eINSTANCE.getOutroTermoRelacional();

    /**
     * The meta object literal for the '<em><b>Operador</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OUTRO_TERMO_RELACIONAL__OPERADOR = eINSTANCE.getOutroTermoRelacional_Operador();

    /**
     * The meta object literal for the '<em><b>Termo</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OUTRO_TERMO_RELACIONAL__TERMO = eINSTANCE.getOutroTermoRelacional_Termo();

    /**
     * The meta object literal for the '{@link br.ufscar.dc.compiladores.alguma.alguma.impl.TermoRelacionalImpl <em>Termo Relacional</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see br.ufscar.dc.compiladores.alguma.alguma.impl.TermoRelacionalImpl
     * @see br.ufscar.dc.compiladores.alguma.alguma.impl.AlgumaPackageImpl#getTermoRelacional()
     * @generated
     */
    EClass TERMO_RELACIONAL = eINSTANCE.getTermoRelacional();

    /**
     * The meta object literal for the '{@link br.ufscar.dc.compiladores.alguma.alguma.impl.TermoComparacaoRelacionalImpl <em>Termo Comparacao Relacional</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see br.ufscar.dc.compiladores.alguma.alguma.impl.TermoComparacaoRelacionalImpl
     * @see br.ufscar.dc.compiladores.alguma.alguma.impl.AlgumaPackageImpl#getTermoComparacaoRelacional()
     * @generated
     */
    EClass TERMO_COMPARACAO_RELACIONAL = eINSTANCE.getTermoComparacaoRelacional();

    /**
     * The meta object literal for the '<em><b>Exp1</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TERMO_COMPARACAO_RELACIONAL__EXP1 = eINSTANCE.getTermoComparacaoRelacional_Exp1();

    /**
     * The meta object literal for the '<em><b>Op Rel</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TERMO_COMPARACAO_RELACIONAL__OP_REL = eINSTANCE.getTermoComparacaoRelacional_OpRel();

    /**
     * The meta object literal for the '<em><b>Exp2</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TERMO_COMPARACAO_RELACIONAL__EXP2 = eINSTANCE.getTermoComparacaoRelacional_Exp2();

    /**
     * The meta object literal for the '{@link br.ufscar.dc.compiladores.alguma.alguma.impl.TermoSubExpressaoRelacionalImpl <em>Termo Sub Expressao Relacional</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see br.ufscar.dc.compiladores.alguma.alguma.impl.TermoSubExpressaoRelacionalImpl
     * @see br.ufscar.dc.compiladores.alguma.alguma.impl.AlgumaPackageImpl#getTermoSubExpressaoRelacional()
     * @generated
     */
    EClass TERMO_SUB_EXPRESSAO_RELACIONAL = eINSTANCE.getTermoSubExpressaoRelacional();

    /**
     * The meta object literal for the '<em><b>Exp Rel</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TERMO_SUB_EXPRESSAO_RELACIONAL__EXP_REL = eINSTANCE.getTermoSubExpressaoRelacional_ExpRel();

    /**
     * The meta object literal for the '{@link br.ufscar.dc.compiladores.alguma.alguma.impl.ComandoImpl <em>Comando</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see br.ufscar.dc.compiladores.alguma.alguma.impl.ComandoImpl
     * @see br.ufscar.dc.compiladores.alguma.alguma.impl.AlgumaPackageImpl#getComando()
     * @generated
     */
    EClass COMANDO = eINSTANCE.getComando();

    /**
     * The meta object literal for the '{@link br.ufscar.dc.compiladores.alguma.alguma.impl.ComandoAtribuicaoImpl <em>Comando Atribuicao</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see br.ufscar.dc.compiladores.alguma.alguma.impl.ComandoAtribuicaoImpl
     * @see br.ufscar.dc.compiladores.alguma.alguma.impl.AlgumaPackageImpl#getComandoAtribuicao()
     * @generated
     */
    EClass COMANDO_ATRIBUICAO = eINSTANCE.getComandoAtribuicao();

    /**
     * The meta object literal for the '<em><b>Exp</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMANDO_ATRIBUICAO__EXP = eINSTANCE.getComandoAtribuicao_Exp();

    /**
     * The meta object literal for the '<em><b>Variavel</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMANDO_ATRIBUICAO__VARIAVEL = eINSTANCE.getComandoAtribuicao_Variavel();

    /**
     * The meta object literal for the '{@link br.ufscar.dc.compiladores.alguma.alguma.impl.ComandoEntradaImpl <em>Comando Entrada</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see br.ufscar.dc.compiladores.alguma.alguma.impl.ComandoEntradaImpl
     * @see br.ufscar.dc.compiladores.alguma.alguma.impl.AlgumaPackageImpl#getComandoEntrada()
     * @generated
     */
    EClass COMANDO_ENTRADA = eINSTANCE.getComandoEntrada();

    /**
     * The meta object literal for the '<em><b>Variavel</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMANDO_ENTRADA__VARIAVEL = eINSTANCE.getComandoEntrada_Variavel();

    /**
     * The meta object literal for the '{@link br.ufscar.dc.compiladores.alguma.alguma.impl.ComandoSaidaImpl <em>Comando Saida</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see br.ufscar.dc.compiladores.alguma.alguma.impl.ComandoSaidaImpl
     * @see br.ufscar.dc.compiladores.alguma.alguma.impl.AlgumaPackageImpl#getComandoSaida()
     * @generated
     */
    EClass COMANDO_SAIDA = eINSTANCE.getComandoSaida();

    /**
     * The meta object literal for the '<em><b>Variavel</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMANDO_SAIDA__VARIAVEL = eINSTANCE.getComandoSaida_Variavel();

    /**
     * The meta object literal for the '{@link br.ufscar.dc.compiladores.alguma.alguma.impl.ComandoCondicaoImpl <em>Comando Condicao</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see br.ufscar.dc.compiladores.alguma.alguma.impl.ComandoCondicaoImpl
     * @see br.ufscar.dc.compiladores.alguma.alguma.impl.AlgumaPackageImpl#getComandoCondicao()
     * @generated
     */
    EClass COMANDO_CONDICAO = eINSTANCE.getComandoCondicao();

    /**
     * The meta object literal for the '<em><b>Exp</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMANDO_CONDICAO__EXP = eINSTANCE.getComandoCondicao_Exp();

    /**
     * The meta object literal for the '<em><b>Cmd1</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMANDO_CONDICAO__CMD1 = eINSTANCE.getComandoCondicao_Cmd1();

    /**
     * The meta object literal for the '<em><b>Cmd2</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMANDO_CONDICAO__CMD2 = eINSTANCE.getComandoCondicao_Cmd2();

    /**
     * The meta object literal for the '{@link br.ufscar.dc.compiladores.alguma.alguma.impl.ComandoRepeticaoImpl <em>Comando Repeticao</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see br.ufscar.dc.compiladores.alguma.alguma.impl.ComandoRepeticaoImpl
     * @see br.ufscar.dc.compiladores.alguma.alguma.impl.AlgumaPackageImpl#getComandoRepeticao()
     * @generated
     */
    EClass COMANDO_REPETICAO = eINSTANCE.getComandoRepeticao();

    /**
     * The meta object literal for the '<em><b>Exp</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMANDO_REPETICAO__EXP = eINSTANCE.getComandoRepeticao_Exp();

    /**
     * The meta object literal for the '<em><b>Cmd</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMANDO_REPETICAO__CMD = eINSTANCE.getComandoRepeticao_Cmd();

    /**
     * The meta object literal for the '{@link br.ufscar.dc.compiladores.alguma.alguma.impl.SubAlgoritmoImpl <em>Sub Algoritmo</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see br.ufscar.dc.compiladores.alguma.alguma.impl.SubAlgoritmoImpl
     * @see br.ufscar.dc.compiladores.alguma.alguma.impl.AlgumaPackageImpl#getSubAlgoritmo()
     * @generated
     */
    EClass SUB_ALGORITMO = eINSTANCE.getSubAlgoritmo();

    /**
     * The meta object literal for the '<em><b>Comandos</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SUB_ALGORITMO__COMANDOS = eINSTANCE.getSubAlgoritmo_Comandos();

  }

} //AlgumaPackage
