/**
 * generated by Xtext 2.27.0.M2
 */
package br.ufscar.dc.compiladores.alguma2.alguma2;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Declaracao</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link br.ufscar.dc.compiladores.alguma2.alguma2.Declaracao#getNome <em>Nome</em>}</li>
 *   <li>{@link br.ufscar.dc.compiladores.alguma2.alguma2.Declaracao#getTipo <em>Tipo</em>}</li>
 * </ul>
 *
 * @see br.ufscar.dc.compiladores.alguma2.alguma2.Alguma2Package#getDeclaracao()
 * @model
 * @generated
 */
public interface Declaracao extends EObject
{
  /**
   * Returns the value of the '<em><b>Nome</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Nome</em>' attribute.
   * @see #setNome(String)
   * @see br.ufscar.dc.compiladores.alguma2.alguma2.Alguma2Package#getDeclaracao_Nome()
   * @model
   * @generated
   */
  String getNome();

  /**
   * Sets the value of the '{@link br.ufscar.dc.compiladores.alguma2.alguma2.Declaracao#getNome <em>Nome</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Nome</em>' attribute.
   * @see #getNome()
   * @generated
   */
  void setNome(String value);

  /**
   * Returns the value of the '<em><b>Tipo</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Tipo</em>' attribute.
   * @see #setTipo(String)
   * @see br.ufscar.dc.compiladores.alguma2.alguma2.Alguma2Package#getDeclaracao_Tipo()
   * @model
   * @generated
   */
  String getTipo();

  /**
   * Sets the value of the '{@link br.ufscar.dc.compiladores.alguma2.alguma2.Declaracao#getTipo <em>Tipo</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Tipo</em>' attribute.
   * @see #getTipo()
   * @generated
   */
  void setTipo(String value);

} // Declaracao
