/**
 * generated by Xtext 2.27.0.M2
 */
package br.ufscar.dc.compiladores.alguma2.alguma2;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

import org.eclipse.xtext.xbase.XExpression;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Programa</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link br.ufscar.dc.compiladores.alguma2.alguma2.Programa#getDeclaracoes <em>Declaracoes</em>}</li>
 *   <li>{@link br.ufscar.dc.compiladores.alguma2.alguma2.Programa#getAlgoritmo <em>Algoritmo</em>}</li>
 * </ul>
 *
 * @see br.ufscar.dc.compiladores.alguma2.alguma2.Alguma2Package#getPrograma()
 * @model
 * @generated
 */
public interface Programa extends EObject
{
  /**
   * Returns the value of the '<em><b>Declaracoes</b></em>' containment reference list.
   * The list contents are of type {@link br.ufscar.dc.compiladores.alguma2.alguma2.Declaracao}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Declaracoes</em>' containment reference list.
   * @see br.ufscar.dc.compiladores.alguma2.alguma2.Alguma2Package#getPrograma_Declaracoes()
   * @model containment="true"
   * @generated
   */
  EList<Declaracao> getDeclaracoes();

  /**
   * Returns the value of the '<em><b>Algoritmo</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Algoritmo</em>' containment reference.
   * @see #setAlgoritmo(XExpression)
   * @see br.ufscar.dc.compiladores.alguma2.alguma2.Alguma2Package#getPrograma_Algoritmo()
   * @model containment="true"
   * @generated
   */
  XExpression getAlgoritmo();

  /**
   * Sets the value of the '{@link br.ufscar.dc.compiladores.alguma2.alguma2.Programa#getAlgoritmo <em>Algoritmo</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Algoritmo</em>' containment reference.
   * @see #getAlgoritmo()
   * @generated
   */
  void setAlgoritmo(XExpression value);

} // Programa
