/*
 * generated by Xtext 2.27.0.M2
 */
package br.ufscar.dc.compiladores.alguma2.ide;

import br.ufscar.dc.compiladores.alguma2.Alguma2RuntimeModule;
import br.ufscar.dc.compiladores.alguma2.Alguma2StandaloneSetup;
import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class Alguma2IdeSetup extends Alguma2StandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new Alguma2RuntimeModule(), new Alguma2IdeModule()));
	}
	
}
