/**
 * generated by Xtext 2.27.0.M2
 */
package br.ufscar.dc.compiladores.alguma.alguma.impl;

import br.ufscar.dc.compiladores.alguma.alguma.*;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;

import org.eclipse.emf.ecore.impl.EFactoryImpl;

import org.eclipse.emf.ecore.plugin.EcorePlugin;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Factory</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class AlgumaFactoryImpl extends EFactoryImpl implements AlgumaFactory
{
  /**
   * Creates the default factory implementation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static AlgumaFactory init()
  {
    try
    {
      AlgumaFactory theAlgumaFactory = (AlgumaFactory)EPackage.Registry.INSTANCE.getEFactory(AlgumaPackage.eNS_URI);
      if (theAlgumaFactory != null)
      {
        return theAlgumaFactory;
      }
    }
    catch (Exception exception)
    {
      EcorePlugin.INSTANCE.log(exception);
    }
    return new AlgumaFactoryImpl();
  }

  /**
   * Creates an instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public AlgumaFactoryImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EObject create(EClass eClass)
  {
    switch (eClass.getClassifierID())
    {
      case AlgumaPackage.PROGRAMA: return createPrograma();
      case AlgumaPackage.DECLARACAO: return createDeclaracao();
      case AlgumaPackage.EXPRESSAO_ARITMETICA: return createExpressaoAritmetica();
      case AlgumaPackage.OUTRO_TERMO_ARITMETICO: return createOutroTermoAritmetico();
      case AlgumaPackage.TERMO_ARITMETICO: return createTermoAritmetico();
      case AlgumaPackage.OUTRO_FATOR_ARITMETICO: return createOutroFatorAritmetico();
      case AlgumaPackage.FATOR_ARITMETICO: return createFatorAritmetico();
      case AlgumaPackage.FATOR_NUMERO: return createFatorNumero();
      case AlgumaPackage.FATOR_VARIAVEL: return createFatorVariavel();
      case AlgumaPackage.FATOR_SUB_EXPRESSAO: return createFatorSubExpressao();
      case AlgumaPackage.EXPRESSAO_RELACIONAL: return createExpressaoRelacional();
      case AlgumaPackage.OUTRO_TERMO_RELACIONAL: return createOutroTermoRelacional();
      case AlgumaPackage.TERMO_RELACIONAL: return createTermoRelacional();
      case AlgumaPackage.TERMO_COMPARACAO_RELACIONAL: return createTermoComparacaoRelacional();
      case AlgumaPackage.TERMO_SUB_EXPRESSAO_RELACIONAL: return createTermoSubExpressaoRelacional();
      case AlgumaPackage.COMANDO: return createComando();
      case AlgumaPackage.COMANDO_ATRIBUICAO: return createComandoAtribuicao();
      case AlgumaPackage.COMANDO_ENTRADA: return createComandoEntrada();
      case AlgumaPackage.COMANDO_SAIDA: return createComandoSaida();
      case AlgumaPackage.COMANDO_CONDICAO: return createComandoCondicao();
      case AlgumaPackage.COMANDO_REPETICAO: return createComandoRepeticao();
      case AlgumaPackage.SUB_ALGORITMO: return createSubAlgoritmo();
      default:
        throw new IllegalArgumentException("The class '" + eClass.getName() + "' is not a valid classifier");
    }
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Programa createPrograma()
  {
    ProgramaImpl programa = new ProgramaImpl();
    return programa;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Declaracao createDeclaracao()
  {
    DeclaracaoImpl declaracao = new DeclaracaoImpl();
    return declaracao;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ExpressaoAritmetica createExpressaoAritmetica()
  {
    ExpressaoAritmeticaImpl expressaoAritmetica = new ExpressaoAritmeticaImpl();
    return expressaoAritmetica;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public OutroTermoAritmetico createOutroTermoAritmetico()
  {
    OutroTermoAritmeticoImpl outroTermoAritmetico = new OutroTermoAritmeticoImpl();
    return outroTermoAritmetico;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public TermoAritmetico createTermoAritmetico()
  {
    TermoAritmeticoImpl termoAritmetico = new TermoAritmeticoImpl();
    return termoAritmetico;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public OutroFatorAritmetico createOutroFatorAritmetico()
  {
    OutroFatorAritmeticoImpl outroFatorAritmetico = new OutroFatorAritmeticoImpl();
    return outroFatorAritmetico;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public FatorAritmetico createFatorAritmetico()
  {
    FatorAritmeticoImpl fatorAritmetico = new FatorAritmeticoImpl();
    return fatorAritmetico;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public FatorNumero createFatorNumero()
  {
    FatorNumeroImpl fatorNumero = new FatorNumeroImpl();
    return fatorNumero;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public FatorVariavel createFatorVariavel()
  {
    FatorVariavelImpl fatorVariavel = new FatorVariavelImpl();
    return fatorVariavel;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public FatorSubExpressao createFatorSubExpressao()
  {
    FatorSubExpressaoImpl fatorSubExpressao = new FatorSubExpressaoImpl();
    return fatorSubExpressao;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ExpressaoRelacional createExpressaoRelacional()
  {
    ExpressaoRelacionalImpl expressaoRelacional = new ExpressaoRelacionalImpl();
    return expressaoRelacional;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public OutroTermoRelacional createOutroTermoRelacional()
  {
    OutroTermoRelacionalImpl outroTermoRelacional = new OutroTermoRelacionalImpl();
    return outroTermoRelacional;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public TermoRelacional createTermoRelacional()
  {
    TermoRelacionalImpl termoRelacional = new TermoRelacionalImpl();
    return termoRelacional;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public TermoComparacaoRelacional createTermoComparacaoRelacional()
  {
    TermoComparacaoRelacionalImpl termoComparacaoRelacional = new TermoComparacaoRelacionalImpl();
    return termoComparacaoRelacional;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public TermoSubExpressaoRelacional createTermoSubExpressaoRelacional()
  {
    TermoSubExpressaoRelacionalImpl termoSubExpressaoRelacional = new TermoSubExpressaoRelacionalImpl();
    return termoSubExpressaoRelacional;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Comando createComando()
  {
    ComandoImpl comando = new ComandoImpl();
    return comando;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ComandoAtribuicao createComandoAtribuicao()
  {
    ComandoAtribuicaoImpl comandoAtribuicao = new ComandoAtribuicaoImpl();
    return comandoAtribuicao;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ComandoEntrada createComandoEntrada()
  {
    ComandoEntradaImpl comandoEntrada = new ComandoEntradaImpl();
    return comandoEntrada;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ComandoSaida createComandoSaida()
  {
    ComandoSaidaImpl comandoSaida = new ComandoSaidaImpl();
    return comandoSaida;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ComandoCondicao createComandoCondicao()
  {
    ComandoCondicaoImpl comandoCondicao = new ComandoCondicaoImpl();
    return comandoCondicao;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ComandoRepeticao createComandoRepeticao()
  {
    ComandoRepeticaoImpl comandoRepeticao = new ComandoRepeticaoImpl();
    return comandoRepeticao;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public SubAlgoritmo createSubAlgoritmo()
  {
    SubAlgoritmoImpl subAlgoritmo = new SubAlgoritmoImpl();
    return subAlgoritmo;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public AlgumaPackage getAlgumaPackage()
  {
    return (AlgumaPackage)getEPackage();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @deprecated
   * @generated
   */
  @Deprecated
  public static AlgumaPackage getPackage()
  {
    return AlgumaPackage.eINSTANCE;
  }

} //AlgumaFactoryImpl
