/**
 * generated by Xtext 2.27.0.M2
 */
package br.ufscar.dc.compiladores.alguma.alguma.impl;

import br.ufscar.dc.compiladores.alguma.alguma.AlgumaPackage;
import br.ufscar.dc.compiladores.alguma.alguma.OutroTermoAritmetico;
import br.ufscar.dc.compiladores.alguma.alguma.TermoAritmetico;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Outro Termo Aritmetico</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link br.ufscar.dc.compiladores.alguma.alguma.impl.OutroTermoAritmeticoImpl#getOperador <em>Operador</em>}</li>
 *   <li>{@link br.ufscar.dc.compiladores.alguma.alguma.impl.OutroTermoAritmeticoImpl#getTermo <em>Termo</em>}</li>
 * </ul>
 *
 * @generated
 */
public class OutroTermoAritmeticoImpl extends MinimalEObjectImpl.Container implements OutroTermoAritmetico
{
  /**
   * The default value of the '{@link #getOperador() <em>Operador</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getOperador()
   * @generated
   * @ordered
   */
  protected static final String OPERADOR_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getOperador() <em>Operador</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getOperador()
   * @generated
   * @ordered
   */
  protected String operador = OPERADOR_EDEFAULT;

  /**
   * The cached value of the '{@link #getTermo() <em>Termo</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTermo()
   * @generated
   * @ordered
   */
  protected TermoAritmetico termo;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected OutroTermoAritmeticoImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return AlgumaPackage.Literals.OUTRO_TERMO_ARITMETICO;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getOperador()
  {
    return operador;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setOperador(String newOperador)
  {
    String oldOperador = operador;
    operador = newOperador;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, AlgumaPackage.OUTRO_TERMO_ARITMETICO__OPERADOR, oldOperador, operador));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public TermoAritmetico getTermo()
  {
    return termo;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetTermo(TermoAritmetico newTermo, NotificationChain msgs)
  {
    TermoAritmetico oldTermo = termo;
    termo = newTermo;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, AlgumaPackage.OUTRO_TERMO_ARITMETICO__TERMO, oldTermo, newTermo);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setTermo(TermoAritmetico newTermo)
  {
    if (newTermo != termo)
    {
      NotificationChain msgs = null;
      if (termo != null)
        msgs = ((InternalEObject)termo).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - AlgumaPackage.OUTRO_TERMO_ARITMETICO__TERMO, null, msgs);
      if (newTermo != null)
        msgs = ((InternalEObject)newTermo).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - AlgumaPackage.OUTRO_TERMO_ARITMETICO__TERMO, null, msgs);
      msgs = basicSetTermo(newTermo, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, AlgumaPackage.OUTRO_TERMO_ARITMETICO__TERMO, newTermo, newTermo));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case AlgumaPackage.OUTRO_TERMO_ARITMETICO__TERMO:
        return basicSetTermo(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case AlgumaPackage.OUTRO_TERMO_ARITMETICO__OPERADOR:
        return getOperador();
      case AlgumaPackage.OUTRO_TERMO_ARITMETICO__TERMO:
        return getTermo();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case AlgumaPackage.OUTRO_TERMO_ARITMETICO__OPERADOR:
        setOperador((String)newValue);
        return;
      case AlgumaPackage.OUTRO_TERMO_ARITMETICO__TERMO:
        setTermo((TermoAritmetico)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case AlgumaPackage.OUTRO_TERMO_ARITMETICO__OPERADOR:
        setOperador(OPERADOR_EDEFAULT);
        return;
      case AlgumaPackage.OUTRO_TERMO_ARITMETICO__TERMO:
        setTermo((TermoAritmetico)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case AlgumaPackage.OUTRO_TERMO_ARITMETICO__OPERADOR:
        return OPERADOR_EDEFAULT == null ? operador != null : !OPERADOR_EDEFAULT.equals(operador);
      case AlgumaPackage.OUTRO_TERMO_ARITMETICO__TERMO:
        return termo != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (operador: ");
    result.append(operador);
    result.append(')');
    return result.toString();
  }

} //OutroTermoAritmeticoImpl
