/*
 * generated by Xtext 2.27.0.M2
 */
package br.ufscar.dc.compiladores.alguma.ui.tests;

import br.ufscar.dc.compiladores.alguma.ui.internal.AlgumaActivator;
import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;

public class AlgumaUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return AlgumaActivator.getInstance().getInjector("br.ufscar.dc.compiladores.alguma.Alguma");
	}

}
