/*
 * generated by Xtext 2.27.0.M2
 */
package br.ufscar.dc.compiladores.alguma2;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class Alguma2RuntimeModule extends AbstractAlguma2RuntimeModule {
}
