/*
 * generated by Xtext 2.27.0.M2
 */
package br.ufscar.dc.compiladores.alguma.ide;


/**
 * Use this class to register ide components.
 */
public class AlgumaIdeModule extends AbstractAlgumaIdeModule {
}
