/*
 * generated by Xtext 2.27.0.M2
 */
package br.ufscar.dc.compiladores.alguma.ui;

import br.ufscar.dc.compiladores.alguma.ui.internal.AlgumaActivator;
import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class AlgumaExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(AlgumaActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		AlgumaActivator activator = AlgumaActivator.getInstance();
		return activator != null ? activator.getInjector(AlgumaActivator.BR_UFSCAR_DC_COMPILADORES_ALGUMA_ALGUMA) : null;
	}

}
