/*
 * generated by Xtext 2.27.0.M2
 */
package br.ufscar.dc.compiladores.alguma2.ui;

import br.ufscar.dc.compiladores.alguma2.ui.internal.Alguma2Activator;
import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class Alguma2ExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(Alguma2Activator.class);
	}
	
	@Override
	protected Injector getInjector() {
		Alguma2Activator activator = Alguma2Activator.getInstance();
		return activator != null ? activator.getInjector(Alguma2Activator.BR_UFSCAR_DC_COMPILADORES_ALGUMA2_ALGUMA2) : null;
	}

}
