/*
 * generated by Xtext 2.27.0.M2
 */
package br.ufscar.dc.compiladores.alguma2.ui.tests;

import br.ufscar.dc.compiladores.alguma2.ui.internal.Alguma2Activator;
import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;

public class Alguma2UiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return Alguma2Activator.getInstance().getInjector("br.ufscar.dc.compiladores.alguma2.Alguma2");
	}

}
